### ISSUE TITLE
Peer to Peer Code Review

### ISSUE THREAD

**Issue by jaimevillegas** [NicolasAndrehh/Leaderboard#2]
Hi @NicolasAndrehh. Good job on your project! We suggest the following adjustments:

- On these two parts you can delete the tags since you are not using them:

https://github.com/NicolasAndrehh/Leaderboard/blob/96585387407c260f081a7e00490384f596cbb524/src/index.html#L10

https://github.com/NicolasAndrehh/Leaderboard/blob/96585387407c260f081a7e00490384f596cbb524/src/index.html#L45

**Comment by NicolasAndrehh** [comment]
Hey @jaimevillegas, thank you so much for your suggestions. I have already implemented them, and you can check out the changes on the development branch. 😄👍
